2023-03-09T15:35:27.777895+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4, 6, 8]
2023-03-09T15:35:27.794167+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4]
2023-03-09T15:35:39.141004+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4, 6, 8]
2023-03-09T15:35:39.152393+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4]
2023-03-09T15:35:39.156393+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (14056), thread 'MainThread' (16916):
Traceback (most recent call last):

> File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 57, in <module>
    print(find_winner(zombies_list[i], plants_list[i]))
          │           │            │   │           └ 1
          │           │            │   └ ([2, 4, 6, 8], [2, 4], [2, 4, 0, 8], [1, 2, 1, 1], [4, 22, 11, 8])
          │           │            └ 1
          │           └ ([1, 3, 5, 7], [1, 3, 5, 7], [1, 3, 5, 7], [2, 1, 1, 1], [12])
          └ <function find_winner at 0x000001D2CD005480>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 43, in find_winner
    return compare_commands_lengths(new_zombies, new_plants, zombies, plants)
           │                        │            │           │        └ [2, 4]
           │                        │            │           └ [1, 3, 5, 7]
           │                        │            └ [2, 4]
           │                        └ [5, 7]
           └ <function compare_commands_lengths at 0x000001D2CD005360>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 26, in compare_commands_lengths
    return is_new_plants_equals_new_zombies(new_plants, new_zombies, zombies, plants)
           │                                │           │            │        └ [2, 4]
           │                                │           │            └ [1, 3, 5, 7]
           │                                │           └ [5, 7]
           │                                └ [2, 4]
           └ <function is_new_plants_equals_new_zombies at 0x000001D2CCFE6B90>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 16, in is_new_plants_equals_new_zombies
    if len(new_zombies) == le(new_plants):
           │                  └ [2, 4]
           └ [5, 7]

NameError: name 'le' is not defined
2023-03-09T15:35:39.202394+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4, 0, 8]
2023-03-09T15:35:39.207395+0200 INFO Enter in the find_winner() function zombies = [2, 1, 1, 1], plants=[1, 2, 1, 1]
2023-03-09T15:35:39.209391+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (14056), thread 'MainThread' (16916):
Traceback (most recent call last):

> File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 57, in <module>
    print(find_winner(zombies_list[i], plants_list[i]))
          │           │            │   │           └ 3
          │           │            │   └ ([2, 4, 6, 8], [2, 4], [2, 4, 0, 8], [1, 2, 1, 1], [4, 22, 11, 8])
          │           │            └ 3
          │           └ ([1, 3, 5, 7], [1, 3, 5, 7], [1, 3, 5, 7], [2, 1, 1, 1], [12])
          └ <function find_winner at 0x000001D2CD005480>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 43, in find_winner
    return compare_commands_lengths(new_zombies, new_plants, zombies, plants)
           │                        │            │           │        └ [1, 2, 1, 1]
           │                        │            │           └ [2, 1, 1, 1]
           │                        │            └ [2]
           │                        └ [2]
           └ <function compare_commands_lengths at 0x000001D2CD005360>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 26, in compare_commands_lengths
    return is_new_plants_equals_new_zombies(new_plants, new_zombies, zombies, plants)
           │                                │           │            │        └ [1, 2, 1, 1]
           │                                │           │            └ [2, 1, 1, 1]
           │                                │           └ [2]
           │                                └ [2]
           └ <function is_new_plants_equals_new_zombies at 0x000001D2CCFE6B90>

  File "c:\Users\Ihor\Documents\Spacelab\tasks\zombies_plants\main.py", line 16, in is_new_plants_equals_new_zombies
    if len(new_zombies) == le(new_plants):
           │                  └ [2]
           └ [2]

NameError: name 'le' is not defined
2023-03-09T15:35:39.249393+0200 INFO Enter in the find_winner() function zombies = [12], plants=[4, 22, 11, 8]
2023-03-09T15:35:39.251392+0200 ERROR IndexError
2023-03-09T15:36:26.994790+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4, 6, 8]
2023-03-09T15:36:27.002828+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4]
2023-03-09T15:36:27.005828+0200 INFO Enter in the find_winner() function zombies = [1, 3, 5, 7], plants=[2, 4, 0, 8]
2023-03-09T15:36:27.009826+0200 INFO Enter in the find_winner() function zombies = [2, 1, 1, 1], plants=[1, 2, 1, 1]
2023-03-09T15:36:27.013825+0200 INFO Enter in the find_winner() function zombies = [12], plants=[4, 22, 11, 8]
2023-03-09T15:36:27.015824+0200 ERROR IndexError
